/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscriptionsIndexRouteImport } from './routes/subscriptions/index'
import { Route as SubscriptionsIdRouteImport } from './routes/subscriptions/$id'
import { Route as SettingsNotifyRouteImport } from './routes/settings/notify'
import { Route as SettingsGeneralRouteImport } from './routes/settings/general'

const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsIndexRoute = SubscriptionsIndexRouteImport.update({
  id: '/subscriptions/',
  path: '/subscriptions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsIdRoute = SubscriptionsIdRouteImport.update({
  id: '/subscriptions/$id',
  path: '/subscriptions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotifyRoute = SettingsNotifyRouteImport.update({
  id: '/settings/notify',
  path: '/settings/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/scheduler': typeof SchedulerRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/notify': typeof SettingsNotifyRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/subscriptions/': typeof SubscriptionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/scheduler': typeof SchedulerRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/notify': typeof SettingsNotifyRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/subscriptions': typeof SubscriptionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/scheduler': typeof SchedulerRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/notify': typeof SettingsNotifyRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/subscriptions/': typeof SubscriptionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/scheduler'
    | '/settings/general'
    | '/settings/notify'
    | '/subscriptions/$id'
    | '/subscriptions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/scheduler'
    | '/settings/general'
    | '/settings/notify'
    | '/subscriptions/$id'
    | '/subscriptions'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/scheduler'
    | '/settings/general'
    | '/settings/notify'
    | '/subscriptions/$id'
    | '/subscriptions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SchedulerRoute: typeof SchedulerRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsNotifyRoute: typeof SettingsNotifyRoute
  SubscriptionsIdRoute: typeof SubscriptionsIdRoute
  SubscriptionsIndexRoute: typeof SubscriptionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/': {
      id: '/subscriptions/'
      path: '/subscriptions'
      fullPath: '/subscriptions/'
      preLoaderRoute: typeof SubscriptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/$id': {
      id: '/subscriptions/$id'
      path: '/subscriptions/$id'
      fullPath: '/subscriptions/$id'
      preLoaderRoute: typeof SubscriptionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notify': {
      id: '/settings/notify'
      path: '/settings/notify'
      fullPath: '/settings/notify'
      preLoaderRoute: typeof SettingsNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SchedulerRoute: SchedulerRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsNotifyRoute: SettingsNotifyRoute,
  SubscriptionsIdRoute: SubscriptionsIdRoute,
  SubscriptionsIndexRoute: SubscriptionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
