/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscriptionsIndexRouteImport } from './routes/subscriptions/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SubscriptionsIdRouteImport } from './routes/subscriptions/$id'
import { Route as SettingsNotifyRouteImport } from './routes/settings/notify'
import { Route as SettingsGeneralRouteImport } from './routes/settings/general'
import { Route as SettingsExportTagsRouteImport } from './routes/settings/export-tags'
import { Route as SettingsExportRouteImport } from './routes/settings/export'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsIndexRoute = SubscriptionsIndexRouteImport.update({
  id: '/subscriptions/',
  path: '/subscriptions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SubscriptionsIdRoute = SubscriptionsIdRouteImport.update({
  id: '/subscriptions/$id',
  path: '/subscriptions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotifyRoute = SettingsNotifyRouteImport.update({
  id: '/notify',
  path: '/notify',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExportTagsRoute = SettingsExportTagsRouteImport.update({
  id: '/export-tags',
  path: '/export-tags',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExportRoute = SettingsExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/rules': typeof RulesRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/account': typeof SettingsAccountRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/export-tags': typeof SettingsExportTagsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/notify': typeof SettingsNotifyRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/subscriptions/': typeof SubscriptionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/rules': typeof RulesRoute
  '/scheduler': typeof SchedulerRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/export-tags': typeof SettingsExportTagsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/notify': typeof SettingsNotifyRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/settings': typeof SettingsIndexRoute
  '/subscriptions': typeof SubscriptionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/rules': typeof RulesRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/account': typeof SettingsAccountRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/export-tags': typeof SettingsExportTagsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/notify': typeof SettingsNotifyRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/subscriptions/': typeof SubscriptionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/rules'
    | '/scheduler'
    | '/settings'
    | '/settings/account'
    | '/settings/export'
    | '/settings/export-tags'
    | '/settings/general'
    | '/settings/notify'
    | '/subscriptions/$id'
    | '/settings/'
    | '/subscriptions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/rules'
    | '/scheduler'
    | '/settings/account'
    | '/settings/export'
    | '/settings/export-tags'
    | '/settings/general'
    | '/settings/notify'
    | '/subscriptions/$id'
    | '/settings'
    | '/subscriptions'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/rules'
    | '/scheduler'
    | '/settings'
    | '/settings/account'
    | '/settings/export'
    | '/settings/export-tags'
    | '/settings/general'
    | '/settings/notify'
    | '/subscriptions/$id'
    | '/settings/'
    | '/subscriptions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RulesRoute: typeof RulesRoute
  SchedulerRoute: typeof SchedulerRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SubscriptionsIdRoute: typeof SubscriptionsIdRoute
  SubscriptionsIndexRoute: typeof SubscriptionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/': {
      id: '/subscriptions/'
      path: '/subscriptions'
      fullPath: '/subscriptions/'
      preLoaderRoute: typeof SubscriptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/subscriptions/$id': {
      id: '/subscriptions/$id'
      path: '/subscriptions/$id'
      fullPath: '/subscriptions/$id'
      preLoaderRoute: typeof SubscriptionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notify': {
      id: '/settings/notify'
      path: '/notify'
      fullPath: '/settings/notify'
      preLoaderRoute: typeof SettingsNotifyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/export-tags': {
      id: '/settings/export-tags'
      path: '/export-tags'
      fullPath: '/settings/export-tags'
      preLoaderRoute: typeof SettingsExportTagsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/export': {
      id: '/settings/export'
      path: '/export'
      fullPath: '/settings/export'
      preLoaderRoute: typeof SettingsExportRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsExportRoute: typeof SettingsExportRoute
  SettingsExportTagsRoute: typeof SettingsExportTagsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsNotifyRoute: typeof SettingsNotifyRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsExportRoute: SettingsExportRoute,
  SettingsExportTagsRoute: SettingsExportTagsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsNotifyRoute: SettingsNotifyRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RulesRoute: RulesRoute,
  SchedulerRoute: SchedulerRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SubscriptionsIdRoute: SubscriptionsIdRoute,
  SubscriptionsIndexRoute: SubscriptionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
