/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscriptionsIndexRouteImport } from './routes/subscriptions/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SubscriptionsIdRouteImport } from './routes/subscriptions/$id'
import { Route as SettingsPlatformsRouteImport } from './routes/settings/platforms'
import { Route as SettingsNotifyRouteImport } from './routes/settings/notify'
import { Route as SettingsGeneralRouteImport } from './routes/settings/general'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsIndexRoute = SubscriptionsIndexRouteImport.update({
  id: '/subscriptions/',
  path: '/subscriptions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SubscriptionsIdRoute = SubscriptionsIdRouteImport.update({
  id: '/subscriptions/$id',
  path: '/subscriptions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPlatformsRoute = SettingsPlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotifyRoute = SettingsNotifyRouteImport.update({
  id: '/notify',
  path: '/notify',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/notify': typeof SettingsNotifyRoute
  '/settings/platforms': typeof SettingsPlatformsRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/subscriptions/': typeof SubscriptionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/scheduler': typeof SchedulerRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/notify': typeof SettingsNotifyRoute
  '/settings/platforms': typeof SettingsPlatformsRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/settings': typeof SettingsIndexRoute
  '/subscriptions': typeof SubscriptionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/notify': typeof SettingsNotifyRoute
  '/settings/platforms': typeof SettingsPlatformsRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/subscriptions/': typeof SubscriptionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/scheduler'
    | '/settings'
    | '/settings/general'
    | '/settings/notify'
    | '/settings/platforms'
    | '/subscriptions/$id'
    | '/settings/'
    | '/subscriptions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/scheduler'
    | '/settings/general'
    | '/settings/notify'
    | '/settings/platforms'
    | '/subscriptions/$id'
    | '/settings'
    | '/subscriptions'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/scheduler'
    | '/settings'
    | '/settings/general'
    | '/settings/notify'
    | '/settings/platforms'
    | '/subscriptions/$id'
    | '/settings/'
    | '/subscriptions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SchedulerRoute: typeof SchedulerRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SubscriptionsIdRoute: typeof SubscriptionsIdRoute
  SubscriptionsIndexRoute: typeof SubscriptionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/': {
      id: '/subscriptions/'
      path: '/subscriptions'
      fullPath: '/subscriptions/'
      preLoaderRoute: typeof SubscriptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/subscriptions/$id': {
      id: '/subscriptions/$id'
      path: '/subscriptions/$id'
      fullPath: '/subscriptions/$id'
      preLoaderRoute: typeof SubscriptionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/platforms': {
      id: '/settings/platforms'
      path: '/platforms'
      fullPath: '/settings/platforms'
      preLoaderRoute: typeof SettingsPlatformsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notify': {
      id: '/settings/notify'
      path: '/notify'
      fullPath: '/settings/notify'
      preLoaderRoute: typeof SettingsNotifyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsNotifyRoute: typeof SettingsNotifyRoute
  SettingsPlatformsRoute: typeof SettingsPlatformsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsNotifyRoute: SettingsNotifyRoute,
  SettingsPlatformsRoute: SettingsPlatformsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SchedulerRoute: SchedulerRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SubscriptionsIdRoute: SubscriptionsIdRoute,
  SubscriptionsIndexRoute: SubscriptionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
