// Code generated by the Encore v1.57.5 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-subs-check-uqti.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the subs-check-uqti Encore application.
 */
export default class Client {
    public readonly auth: auth.ServiceClient
    public readonly checker: checker.ServiceClient
    public readonly notify: notify.ServiceClient
    public readonly scheduler: scheduler.ServiceClient
    public readonly settings: settings.ServiceClient
    public readonly subscription: subscription.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * @deprecated This constructor is deprecated, and you should move to using BaseURL with an Options object
     */
    constructor(target: string, token?: string)

    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions)
    constructor(target: string | BaseURL = "prod", options?: string | ClientOptions) {

        // Convert the old constructor parameters to a BaseURL object and a ClientOptions object
        if (!target.startsWith("http://") && !target.startsWith("https://")) {
            target = Environment(target)
        }

        if (typeof options === "string") {
            options = { auth: options }
        }

        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.auth = new auth.ServiceClient(base)
        this.checker = new checker.ServiceClient(base)
        this.notify = new notify.ServiceClient(base)
        this.scheduler = new scheduler.ServiceClient(base)
        this.settings = new settings.ServiceClient(base)
        this.subscription = new subscription.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the auth token to be used for each request
     * either by passing in a static token string or by passing in a function
     * which returns the auth token.
     *
     * These tokens will be sent as bearer tokens in the Authorization header.
     */
    auth?: string | AuthDataGenerator
}

/**
 * services/auth/auth.go
 */
export namespace auth {
    export interface LoginParams {
        username: string
        password: string
        remember: boolean
    }

    export interface LoginResponse {
        token: string
        "user_id": string
    }

    export interface MeResponse {
        "user_id": string
        username: string
    }

    export interface RegisterParams {
        username: string
        password: string
    }

    export interface RegisterResponse {
        "user_id": string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.Login = this.Login.bind(this)
            this.Me = this.Me.bind(this)
            this.Register = this.Register.bind(this)
        }

        public async Login(params: LoginParams): Promise<LoginResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/auth/login`, JSON.stringify(params))
            return await resp.json() as LoginResponse
        }

        public async Me(): Promise<MeResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/auth/me`)
            return await resp.json() as MeResponse
        }

        public async Register(params: RegisterParams): Promise<RegisterResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/auth/register`, JSON.stringify(params))
            return await resp.json() as RegisterResponse
        }
    }
}

/**
 * services/checker/checker.go
 */
export namespace checker {
    /**
     * CheckOptions controls which tests are run per node.
     */
    export interface CheckOptions {
        "speed_test": boolean
        "upload_speed_test": boolean
        "media_apps": string[]
        debug: boolean
    }

    /**
     * CreateRuleParams is the request body for POST /platform-rules.
     */
    export interface CreateRuleParams {
        name: string
        key: string
        icon: string
        enabled: boolean
        "rule_type": string
        definition: JSONValue
        "sort_order": number
    }

    /**
     * DebugStep captures one step in a platform check trace.
     */
    export interface DebugStep {
        /**
         * "http_request" | "http_response" | "variable" | "condition" | "log" | "error"
         */
        type: string

        /**
         * human-readable summary
         */
        description: string

        /**
         * free-form key-value pairs as JSON
         */
        details: JSONValue
    }

    /**
     * DebugTrace is the full trace for one platform check on one node.
     */
    export interface DebugTrace {
        platform: string
        result: boolean
        steps: DebugStep[]
    }

    /**
     * ExportLog is one export request record.
     */
    export interface ExportLog {
        id: string
        ip: string
        "requested_at": string
    }

    /**
     * ExportLogsResponse is returned by GET /export-logs/:subscriptionID.
     */
    export interface ExportLogsResponse {
        logs: ExportLog[]
    }

    /**
     * GetResultsParams are the query parameters for GET /check/:subscriptionID/results.
     */
    export interface GetResultsParams {
        JobID: string
    }

    /**
     * ImportNodesParams is the request body for ImportNodes.
     */
    export interface ImportNodesParams {
        /**
         * Content is a subscription payload pasted by the user: Clash YAML
         * (proxies:) or a V2Ray base64 blob / share links — same formats the URL
         * fetcher accepts.
         */
        content: string
    }

    /**
     * ImportNodesResponse reports how many nodes were imported.
     */
    export interface ImportNodesResponse {
        count: number
    }

    /**
     * Job represents a check job.
     */
    export interface Job {
        id: string
        "subscription_id": string
        status: string
        total: number
        progress: number
        "created_at": string
        "finished_at": string
        "total_traffic_bytes": number
    }

    /**
     * JobSummary is one entry in the job history list.
     */
    export interface JobSummary {
        id: string
        "subscription_id": string
        status: string
        total: number
        available: number
        "speed_test": boolean
        "media_apps": string[]
        "created_at": string
        "finished_at": string
        "total_traffic_bytes": number
    }

    /**
     * LatestJobSummary is the most recent check job for one subscription.
     */
    export interface LatestJobSummary {
        id: string
        status: string
        available: number
        total: number
        "avg_latency_ms": number
        "created_at": string
        "finished_at": string
    }

    /**
     * LatestJobsResponse maps subscription ID → latest job summary.
     */
    export interface LatestJobsResponse {
        jobs: { [key: string]: LatestJobSummary }
    }

    /**
     * ListJobsParams are the query parameters for GET /check/:subscriptionID/jobs.
     */
    export interface ListJobsParams {
        Limit: number
        Offset: number
    }

    /**
     * ListJobsResponse is returned by GET /check/:subscriptionID/jobs.
     */
    export interface ListJobsResponse {
        jobs: JobSummary[]
        total: number
    }

    /**
     * ListRulesResponse is returned by GET /platform-rules.
     */
    export interface ListRulesResponse {
        rules: PlatformRule[]
    }

    /**
     * ListTestNodesResponse is returned by GET /platform-rules/test-nodes.
     */
    export interface ListTestNodesResponse {
        nodes: NodeSummary[]
    }

    /**
     * LocalUnlockResult holds platform accessibility from the server's own network.
     */
    export interface LocalUnlockResult {
        platforms: { [key: string]: PlatformOutcome }
        ip: string
        country: string
    }

    /**
     * NodeResult represents a single node's check result for the API response.
     */
    export interface NodeResult {
        "node_id": string
        "node_name": string
        "node_type": string
        enabled: boolean
        alive: boolean
        "latency_ms": number
        "speed_kbps": number
        "upload_speed_kbps": number
        country: string
        ip: string
        server: string
        port: number
        config: string
        platforms: { [key: string]: PlatformOutcome }
        "traffic_bytes": number
    }

    /**
     * NodeSummary is a minimal proxy node entry for the test node picker.
     */
    export interface NodeSummary {
        id: string
        name: string
        type: string
        /**
         * Config is the node's proxy config JSON, used when selecting a node to
         * tunnel a subscription fetch through.
         */
        config: string
    }

    /**
     * PlatformOutcome is the result of evaluating one platform rule for one node.
     */
    export interface PlatformOutcome {
        unlocked: boolean
        status: string
        region: string
    }

    /**
     * PlatformRule is a user-defined platform detection rule.
     */
    export interface PlatformRule {
        id: string
        "user_id": string
        name: string
        key: string
        icon: string
        enabled: boolean
        "rule_type": string
        definition: JSONValue
        "is_default": boolean
        customized: boolean
        "sort_order": number
        "created_at": string
        "updated_at": string
    }

    /**
     * RefreshResponse reports how many nodes a refresh produced.
     */
    export interface RefreshResponse {
        count: number
    }

    /**
     * ResultsResponse is returned by GET /check/:subscriptionID/results.
     */
    export interface ResultsResponse {
        job: Job
        results: NodeResult[]
    }

    /**
     * SetNodeEnabledParams is the request body for PATCH /nodes/:nodeID.
     */
    export interface SetNodeEnabledParams {
        enabled: boolean
    }

    /**
     * TestFetchResponse reports whether a dry-run fetch succeeded. A failure is
     * returned in-band (HTTP 200, ok=false, error set) so the UI can show the exact
     * reason instead of a generic request error.
     */
    export interface TestFetchResponse {
        ok: boolean
        count: number
        error: string
    }

    /**
     * TestRuleParams is the request body for POST /platform-rules/test.
     */
    export interface TestRuleParams {
        "rule_type": string
        definition: JSONValue
        "node_id": string
    }

    /**
     * TestRuleResult is returned by POST /platform-rules/test.
     */
    export interface TestRuleResult {
        ok: boolean
        error: string
        "status_code": number
        "final_url": string
        body: string
        "response_headers": { [key: string]: string }
        "node_name": string
        "duration_ms": number
        trace: DebugTrace
    }

    /**
     * TriggerParams is the optional request body for POST /check/:subscriptionID.
     */
    export interface TriggerParams {
        "speed_test": boolean
        "upload_speed_test": boolean
        "media_apps": string[]
        debug: boolean
    }

    /**
     * TriggerResponse is returned by POST /check/:subscriptionID.
     */
    export interface TriggerResponse {
        "job_id": string
    }

    /**
     * UpdateRuleParams is the request body for PUT /platform-rules/:ruleId.
     */
    export interface UpdateRuleParams {
        name: string
        icon: string
        enabled: boolean
        "rule_type": string
        definition: JSONValue
        "sort_order": number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.CancelCheck = this.CancelCheck.bind(this)
            this.CreateRule = this.CreateRule.bind(this)
            this.DeleteRule = this.DeleteRule.bind(this)
            this.Export = this.Export.bind(this)
            this.GetExportLogs = this.GetExportLogs.bind(this)
            this.GetLocalUnlock = this.GetLocalUnlock.bind(this)
            this.GetProgress = this.GetProgress.bind(this)
            this.GetResults = this.GetResults.bind(this)
            this.ImportNodes = this.ImportNodes.bind(this)
            this.LatestJobs = this.LatestJobs.bind(this)
            this.ListJobs = this.ListJobs.bind(this)
            this.ListRules = this.ListRules.bind(this)
            this.ListTestNodes = this.ListTestNodes.bind(this)
            this.RefreshSubscription = this.RefreshSubscription.bind(this)
            this.ResetRule = this.ResetRule.bind(this)
            this.SetNodeEnabled = this.SetNodeEnabled.bind(this)
            this.TestFetch = this.TestFetch.bind(this)
            this.TestRule = this.TestRule.bind(this)
            this.TriggerCheck = this.TriggerCheck.bind(this)
            this.UpdateRule = this.UpdateRule.bind(this)
        }

        /**
         * CancelCheck stops a running check job.
         */
        public async CancelCheck(jobID: string): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/check/${encodeURIComponent(jobID)}`)
        }

        /**
         * CreateRule creates a new platform rule for the current user.
         */
        public async CreateRule(params: CreateRuleParams): Promise<PlatformRule> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/platform-rules`, JSON.stringify(params))
            return await resp.json() as PlatformRule
        }

        /**
         * DeleteRule removes a platform rule owned by the current user.
         */
        public async DeleteRule(ruleId: string): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/platform-rules/${encodeURIComponent(ruleId)}`)
        }

        /**
         * Export generates a subscription link from the latest completed check results.
         * If subscriptionID is "all", combines nodes from all subscriptions.
         * 
         * Supported targets: clash (default), base64, routeros
         * For routeros target, use ?list=<address-list-name> (default: clash_servers)
         */
        public async Export(method: "GET", subscriptionID: string, body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/export/${encodeURIComponent(subscriptionID)}`, body, options)
        }

        /**
         * GetExportLogs returns the export request log for a subscription.
         */
        public async GetExportLogs(subscriptionID: string): Promise<ExportLogsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/export-logs/${encodeURIComponent(subscriptionID)}`)
            return await resp.json() as ExportLogsResponse
        }

        /**
         * GetLocalUnlock checks which platforms are accessible from the server's own
         * network, running the current user's ENABLED rules (not the hardcoded defaults).
         */
        public async GetLocalUnlock(): Promise<LocalUnlockResult> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/network-unlock`)
            return await resp.json() as LocalUnlockResult
        }

        /**
         * GetProgress streams real-time check progress via SSE.
         */
        public async GetProgress(method: "GET", jobID: string, body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/check/${encodeURIComponent(jobID)}/progress`, body, options)
        }

        /**
         * GetResults returns the latest check results for a subscription.
         */
        public async GetResults(subscriptionID: string, params: GetResultsParams): Promise<ResultsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "job_id": params.JobID,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/check/${encodeURIComponent(subscriptionID)}/results`, undefined, {query})
            return await resp.json() as ResultsResponse
        }

        /**
         * ImportNodes replaces a subscription's node list from pasted content instead of
         * a URL fetch. Lets users populate subscriptions whose URL is unreachable from
         * the server. The imported list persists until the next manual import or
         * refresh — checks never overwrite it.
         */
        public async ImportNodes(subscriptionID: string, params: ImportNodesParams): Promise<ImportNodesResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/subscription/${encodeURIComponent(subscriptionID)}/import-nodes`, JSON.stringify(params))
            return await resp.json() as ImportNodesResponse
        }

        /**
         * LatestJobs returns the most recent check job per subscription for the
         * current user, with the alive-node average latency. Powers the workbench
         * subscription list and the scheduler's "Last check" column in one request.
         */
        public async LatestJobs(): Promise<LatestJobsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/check-summaries`)
            return await resp.json() as LatestJobsResponse
        }

        /**
         * ListJobs returns paginated check job history for a subscription.
         */
        public async ListJobs(subscriptionID: string, params: ListJobsParams): Promise<ListJobsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  String(params.Limit),
                offset: String(params.Offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/check/${encodeURIComponent(subscriptionID)}/jobs`, undefined, {query})
            return await resp.json() as ListJobsResponse
        }

        /**
         * ListRules returns all platform rules for the current user.
         * Seeds default rules on first call if none exist.
         */
        public async ListRules(): Promise<ListRulesResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/platform-rules`)
            return await resp.json() as ListRulesResponse
        }

        /**
         * ListTestNodes returns all proxy nodes available to the current user, for the test node picker.
         */
        public async ListTestNodes(): Promise<ListTestNodesResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/platform-rules/test-nodes`)
            return await resp.json() as ListTestNodesResponse
        }

        /**
         * RefreshSubscription re-fetches the subscription URL and replaces its node
         * list. This is the explicit, manual counterpart to the old per-check fetch:
         * nodes only change when the user asks for it.
         */
        public async RefreshSubscription(subscriptionID: string): Promise<RefreshResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/subscription/${encodeURIComponent(subscriptionID)}/refresh`)
            return await resp.json() as RefreshResponse
        }

        /**
         * ResetRule restores a built-in rule to its seeded default and clears the
         * customized flag. The enabled state is preserved.
         */
        public async ResetRule(ruleId: string): Promise<PlatformRule> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/platform-rule-reset/${encodeURIComponent(ruleId)}`)
            return await resp.json() as PlatformRule
        }

        /**
         * SetNodeEnabled enables or disables a single node for the authenticated user.
         * Disabled nodes are excluded from subscription exports but still appear in results.
         */
        public async SetNodeEnabled(nodeID: string, params: SetNodeEnabledParams): Promise<void> {
            await this.baseClient.callTypedAPI("PATCH", `/nodes/${encodeURIComponent(nodeID)}`, JSON.stringify(params))
        }

        /**
         * TestFetch tries to fetch the subscription URL without persisting anything, so
         * the user can check whether the server can reach the provider and how many
         * nodes it would get.
         */
        public async TestFetch(subscriptionID: string): Promise<TestFetchResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/subscription/${encodeURIComponent(subscriptionID)}/test-fetch`)
            return await resp.json() as TestFetchResponse
        }

        /**
         * TestRule runs a rule definition and returns verbose debug output.
         * If NodeID is set, the request is routed through that node's proxy.
         */
        public async TestRule(params: TestRuleParams): Promise<TestRuleResult> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/platform-rules/test`, JSON.stringify(params))
            return await resp.json() as TestRuleResult
        }

        /**
         * TriggerCheck creates a new check job for the given subscription.
         */
        public async TriggerCheck(subscriptionID: string, params: TriggerParams): Promise<TriggerResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/check/${encodeURIComponent(subscriptionID)}`, JSON.stringify(params))
            return await resp.json() as TriggerResponse
        }

        /**
         * UpdateRule updates a platform rule owned by the current user.
         */
        public async UpdateRule(ruleId: string, params: UpdateRuleParams): Promise<PlatformRule> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/platform-rules/${encodeURIComponent(ruleId)}`, JSON.stringify(params))
            return await resp.json() as PlatformRule
        }
    }
}

/**
 * services/notify/notify.go
 */
export namespace notify {
    /**
     * Channel represents a notification channel.
     */
    export interface Channel {
        id: string
        "user_id": string
        name: string
        type: string
        config: JSONValue
        enabled: boolean
        "on_check_complete": boolean
        "unlock_cron": string
        "platform_alerts": string[]
        "created_at": string
    }

    /**
     * CreateChannelParams is the request body for POST /notify/channels.
     */
    export interface CreateChannelParams {
        name: string
        type: string
        config: JSONValue
        "on_check_complete": boolean
        "unlock_cron": string
        "platform_alerts": string[]
    }

    /**
     * DeleteChannelResponse is the response for DELETE /notify/channels/:id.
     */
    export interface DeleteChannelResponse {
        ok: boolean
    }

    /**
     * ListChannelsResponse is the response for GET /notify/channels.
     */
    export interface ListChannelsResponse {
        channels: Channel[]
    }

    /**
     * TestChannelParams selects which report type to test.
     */
    export interface TestChannelParams {
        /**
         * "check", "unlock", or "platform_alert"
         */
        "report_type": string
    }

    /**
     * TestChannelResponse is the response for POST /notify/channels/:id/test.
     */
    export interface TestChannelResponse {
        ok: boolean
        error: string
    }

    /**
     * UpdateChannelParams is the request body for PUT /notify/channels/:id.
     */
    export interface UpdateChannelParams {
        name: string
        config: JSONValue
        enabled: boolean
        "on_check_complete": boolean
        "unlock_cron": string
        "platform_alerts": string[]
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.CreateChannel = this.CreateChannel.bind(this)
            this.DeleteChannel = this.DeleteChannel.bind(this)
            this.ListChannels = this.ListChannels.bind(this)
            this.TestChannel = this.TestChannel.bind(this)
            this.UpdateChannel = this.UpdateChannel.bind(this)
        }

        /**
         * CreateChannel adds a new notification channel.
         */
        public async CreateChannel(params: CreateChannelParams): Promise<Channel> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/notify/channels`, JSON.stringify(params))
            return await resp.json() as Channel
        }

        /**
         * DeleteChannel removes a notification channel.
         */
        public async DeleteChannel(id: string): Promise<DeleteChannelResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/notify/channels/${encodeURIComponent(id)}`)
            return await resp.json() as DeleteChannelResponse
        }

        /**
         * ListChannels returns all notification channels for the current user.
         */
        public async ListChannels(): Promise<ListChannelsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/notify/channels`)
            return await resp.json() as ListChannelsResponse
        }

        /**
         * TestChannel sends a test notification to verify the channel configuration.
         */
        public async TestChannel(id: string, params: TestChannelParams): Promise<TestChannelResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/notify/channels/${encodeURIComponent(id)}/test`, JSON.stringify(params))
            return await resp.json() as TestChannelResponse
        }

        /**
         * UpdateChannel modifies an existing notification channel.
         */
        public async UpdateChannel(id: string, params: UpdateChannelParams): Promise<Channel> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/notify/channels/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as Channel
        }
    }
}

/**
 * services/scheduler/scheduler.go
 */
export namespace scheduler {
    /**
     * CreateParams is the request body for POST /scheduler.
     */
    export interface CreateParams {
        "subscription_id": string
        "cron_expr": string
        options: checker.CheckOptions
    }

    /**
     * DeleteResponse is the response for DELETE /scheduler/:id.
     */
    export interface DeleteResponse {
        ok: boolean
    }

    /**
     * ListResponse is the response for GET /scheduler.
     */
    export interface ListResponse {
        jobs: ScheduledJob[]
    }

    /**
     * ScheduledJob represents a cron schedule entry.
     */
    export interface ScheduledJob {
        id: string
        "subscription_id": string
        "cron_expr": string
        enabled: boolean
        "speed_test": boolean
        "upload_speed_test": boolean
        "media_apps": string[]
        debug: boolean
        "created_at": string
    }

    /**
     * SetEnabledParams is the request body for PATCH /scheduler/:id.
     */
    export interface SetEnabledParams {
        enabled: boolean
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.Create = this.Create.bind(this)
            this.Delete = this.Delete.bind(this)
            this.List = this.List.bind(this)
            this.SetEnabled = this.SetEnabled.bind(this)
        }

        /**
         * Create adds or updates a cron schedule for a subscription.
         */
        public async Create(params: CreateParams): Promise<ScheduledJob> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/scheduler`, JSON.stringify(params))
            return await resp.json() as ScheduledJob
        }

        /**
         * Delete removes a scheduled job by ID.
         */
        public async Delete(id: string): Promise<DeleteResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/scheduler/${encodeURIComponent(id)}`)
            return await resp.json() as DeleteResponse
        }

        /**
         * List returns all scheduled jobs for the current user.
         */
        public async List(): Promise<ListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/scheduler`)
            return await resp.json() as ListResponse
        }

        /**
         * SetEnabled pauses or resumes a scheduled job without deleting it.
         */
        public async SetEnabled(id: string, params: SetEnabledParams): Promise<ScheduledJob> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/scheduler/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as ScheduledJob
        }
    }
}

/**
 * services/settings/settings.go
 */
export namespace settings {
    /**
     * APIKeyResponse is returned by GET /settings/api-key and POST /settings/api-key/regenerate.
     */
    export interface APIKeyResponse {
        "api_key": string
    }

    /**
     * EmailConfig holds global SMTP settings for email notifications.
     * The recipient address is configured per-channel in the notify service.
     */
    export interface EmailConfig {
        "smtp_host": string
        "smtp_port": number
        "smtp_user": string
        "smtp_pass": string
        from: string
    }

    /**
     * ExportTagConfig controls the tags appended to node names in exports.
     */
    export interface ExportTagConfig {
        "show_country": boolean
        "show_speed": boolean
        platforms: PlatformTag[]
    }

    /**
     * PlatformTag is one platform's export-tag rule. Key is a built-in platform
     * (netflix, openai, …) or a custom rule key (e.g. spotify).
     */
    export interface PlatformTag {
        key: string
        label: string
        enabled: boolean
    }

    /**
     * UserSettings holds configurable per-user settings.
     */
    export interface UserSettings {
        "speed_test_url": string
        "upload_test_url": string
        "latency_test_url": string
        "email_config": EmailConfig
        "export_tags": ExportTagConfig
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.GetAPIKey = this.GetAPIKey.bind(this)
            this.GetSettings = this.GetSettings.bind(this)
            this.RegenerateAPIKey = this.RegenerateAPIKey.bind(this)
            this.UpdateSettings = this.UpdateSettings.bind(this)
        }

        /**
         * GetAPIKey returns the user's API key, generating one if it doesn't exist yet.
         */
        public async GetAPIKey(): Promise<APIKeyResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/settings/api-key`)
            return await resp.json() as APIKeyResponse
        }

        /**
         * GetSettings returns the current user's settings.
         */
        public async GetSettings(): Promise<UserSettings> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/settings`)
            return await resp.json() as UserSettings
        }

        /**
         * RegenerateAPIKey creates a new API key, invalidating the old one.
         */
        public async RegenerateAPIKey(): Promise<APIKeyResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/settings/api-key/regenerate`)
            return await resp.json() as APIKeyResponse
        }

        /**
         * UpdateSettings updates the current user's settings.
         */
        public async UpdateSettings(params: UserSettings): Promise<UserSettings> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/settings`, JSON.stringify(params))
            return await resp.json() as UserSettings
        }
    }
}

/**
 * services/subscription/subscription.go
 */
export namespace subscription {
    /**
     * CreateParams is the request body for POST /subscriptions.
     */
    export interface CreateParams {
        name: string
        url: string
        "cron_expr": string
        "export_include_dead": boolean
        "export_sort": string
    }

    /**
     * DeleteResponse is the response for DELETE /subscriptions/:id.
     */
    export interface DeleteResponse {
        ok: boolean
    }

    /**
     * ListResponse is the response for GET /subscriptions.
     */
    export interface ListResponse {
        subscriptions: Subscription[]
    }

    /**
     * SetFetchProxyParams sets (or clears) the node used to tunnel subscription
     * fetches. Config is the chosen node's proxy config as JSON; an empty string
     * clears it (fetch directly).
     */
    export interface SetFetchProxyParams {
        config: string
    }

    /**
     * Subscription represents a proxy subscription link.
     */
    export interface Subscription {
        id: string
        "user_id": string
        name: string
        url: string
        enabled: boolean
        "cron_expr": string
        "created_at": string
        "last_run_at": string
        "export_include_dead": boolean
        "export_sort": string
        /**
         * FetchProxyConfig, when non-empty, is the JSON of a node's proxy config
         * used to tunnel the subscription fetch through that node (for URLs the
         * server can't reach directly). Empty means fetch directly. Stored as
         * jsonb, surfaced as a JSON string so it crosses the Encore API boundary.
         */
        "fetch_proxy_config": string
    }

    /**
     * UpdateParams is the request body for PUT /subscriptions/:id.
     * Use ClearCronExpr=true to remove the cron schedule (set cron_expr to NULL).
     */
    export interface UpdateParams {
        name: string
        url: string
        enabled: boolean
        "cron_expr": string
        "clear_cron_expr": boolean
        "export_include_dead": boolean
        "export_sort": string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.Create = this.Create.bind(this)
            this.Delete = this.Delete.bind(this)
            this.GetSubscription = this.GetSubscription.bind(this)
            this.List = this.List.bind(this)
            this.SetFetchProxy = this.SetFetchProxy.bind(this)
            this.Update = this.Update.bind(this)
        }

        /**
         * Create adds a new subscription for the current user.
         */
        public async Create(params: CreateParams): Promise<Subscription> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/subscriptions`, JSON.stringify(params))
            return await resp.json() as Subscription
        }

        /**
         * Delete removes a subscription owned by the current user.
         */
        public async Delete(id: string): Promise<DeleteResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/subscriptions/${encodeURIComponent(id)}`)
            return await resp.json() as DeleteResponse
        }

        /**
         * GetSubscription returns a subscription by ID, verifying ownership.
         * Used internally by the checker service.
         */
        public async GetSubscription(id: string): Promise<Subscription> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/subscriptions/${encodeURIComponent(id)}`)
            return await resp.json() as Subscription
        }

        /**
         * List returns all subscriptions for the current user.
         */
        public async List(): Promise<ListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/subscriptions`)
            return await resp.json() as ListResponse
        }

        /**
         * SetFetchProxy stores the chosen node's proxy config on the subscription so
         * refresh / test-fetch tunnel the download through that node. Pass an empty
         * config to go back to a direct fetch.
         */
        public async SetFetchProxy(id: string, params: SetFetchProxyParams): Promise<Subscription> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/subscriptions/${encodeURIComponent(id)}/fetch-proxy`, JSON.stringify(params))
            return await resp.json() as Subscription
        }

        /**
         * Update modifies a subscription owned by the current user.
         */
        public async Update(id: string, params: UpdateParams): Promise<Subscription> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/subscriptions/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as Subscription
        }
    }
}

// JSONValue represents an arbitrary JSON value.
export type JSONValue = string | number | boolean | null | JSONValue[] | {[key: string]: JSONValue}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | string
  | Promise<string | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "subs-check-uqti-Generated-TS-Client (Encore/v1.57.5)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: string | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = {};
            data.headers["Authorization"] = "Bearer " + authData;

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
